"""Step registry — all 200 autonomous execution steps across 7 domains."""
from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class Step:
    number: int
    name: str
    domain: str
    description: str
    auto_trigger: bool = True
    requires_steps: list[int] = field(default_factory=list)


STEP_REGISTRY: dict[int, Step] = {}


def _reg(*steps: Step) -> None:
    for s in steps:
        STEP_REGISTRY[s.number] = s


# ── DOMAIN 1: CARRIER ONBOARDING (1–30) ──────────────────────────────────────
_reg(
    Step(1,  "intake.receive",            "onboarding", "Receive carrier intake form submission"),
    Step(2,  "intake.dedupe_check",       "onboarding", "Deduplicate carrier by MC/DOT/EIN", requires_steps=[1]),
    Step(3,  "fmcsa.lookup",              "onboarding", "Query FMCSA SAFER API for authority status", requires_steps=[2]),
    Step(4,  "fmcsa.csa_score",           "onboarding", "Pull CSA BASIC scores from FMCSA", requires_steps=[3]),
    Step(5,  "shield.safety_light",       "onboarding", "Evaluate safety light (green/yellow/red)", requires_steps=[4]),
    Step(6,  "insurance.verify",          "onboarding", "Verify insurance certificates via FMCSA", requires_steps=[3]),
    Step(7,  "insurance.expiry_watch",    "onboarding", "Schedule insurance expiry alert", requires_steps=[6]),
    Step(8,  "eld.detect_provider",       "onboarding", "Detect ELD provider (Motive/Samsara/Geotab)", requires_steps=[1]),
    Step(9,  "eld.sync_credentials",      "onboarding", "Sync ELD API credentials to fleet record", requires_steps=[8]),
    Step(10, "banking.collect",           "onboarding", "Collect banking / ACH information", requires_steps=[1]),
    Step(11, "banking.verify",            "onboarding", "Micro-deposit or Plaid verification of bank account", requires_steps=[10]),
    Step(12, "stripe.create_customer",    "onboarding", "Create Stripe customer record", requires_steps=[1]),
    Step(13, "stripe.attach_subscription","onboarding", "Attach founders/pro subscription plan", requires_steps=[12]),
    Step(14, "esign.send_agreement",      "onboarding", "Send carrier agreement for e-signature", requires_steps=[5, 6]),
    Step(15, "esign.track_completion",    "onboarding", "Poll e-signature status until complete", requires_steps=[14]),
    Step(16, "clm.ingest_agreement",      "onboarding", "Ingest signed carrier agreement into CLM", requires_steps=[15]),
    Step(17, "carrier.set_active",        "onboarding", "Set carrier status to active", requires_steps=[15, 11]),
    Step(18, "inventory.decrement",       "onboarding", "Decrement founders inventory slot", requires_steps=[17]),
    Step(19, "nova.welcome_email",        "onboarding", "Send welcome email via Postmark", requires_steps=[17]),
    Step(20, "vance.welcome_call",        "onboarding", "Trigger Bland AI welcome/onboarding voice call", requires_steps=[17]),
    Step(21, "document_vault.create_folder", "onboarding", "Create carrier document vault folder", requires_steps=[17]),
    Step(22, "document_vault.upload_agreement", "onboarding", "Upload signed agreement to document vault", requires_steps=[16, 21]),
    Step(23, "atlas.schedule_check_in",   "onboarding", "Schedule 7-day check-in with carrier", requires_steps=[17]),
    Step(24, "beacon.activate_dashboard", "onboarding", "Activate carrier in EAGLE EYE dashboard", requires_steps=[17]),
    Step(25, "mc_loyalty.check",          "onboarding", "Check MC loyalty — canceled MCs get $400 rate tier", requires_steps=[3]),
    Step(26, "lead.convert_to_carrier",   "onboarding", "Convert lead record to active carrier", requires_steps=[17]),
    Step(27, "airtable.sync_record",      "onboarding", "Sync carrier record to Airtable", requires_steps=[17]),
    Step(28, "signal.notify_commander",   "onboarding", "Notify Commander of new carrier activation", requires_steps=[17]),
    Step(29, "fleet.create_asset",        "onboarding", "Create fleet asset record for each truck", requires_steps=[17]),
    Step(30, "onboarding.complete",       "onboarding", "Mark onboarding complete — write atomic ledger event", requires_steps=list(range(17, 30))),
)

# ── DOMAIN 2: LOAD DISPATCH (31–60) ──────────────────────────────────────────
_reg(
    Step(31, "dispatch.load_received",    "dispatch", "Receive new load from broker or shipper"),
    Step(32, "clm.scan_rate_conf",        "dispatch", "Scan rate confirmation with Claude CLM scanner", requires_steps=[31]),
    Step(33, "clm.validate_rate",         "dispatch", "Validate rate against market benchmarks", requires_steps=[32]),
    Step(34, "dispatch.match_truck",      "dispatch", "Match load to available truck by equipment/HOS/location", requires_steps=[32]),
    Step(35, "dispatch.score_match",      "dispatch", "Score truck-load match (proximity, margin, HOS hours)", requires_steps=[34]),
    Step(36, "dispatch.offer_load",       "dispatch", "Offer load to driver via PWA notification", requires_steps=[35]),
    Step(37, "dispatch.driver_accept",    "dispatch", "Receive driver acceptance from PWA", requires_steps=[36]),
    Step(38, "dispatch.reoffer_on_decline","dispatch", "Re-offer to next ranked truck if declined", requires_steps=[36]),
    Step(39, "eld.lock_hos",              "dispatch", "Lock driver HOS hours in ELD for this load", requires_steps=[37]),
    Step(40, "clm.create_load_contract",  "dispatch", "Create contract record linking rate conf to load", requires_steps=[32, 37]),
    Step(41, "dispatch.confirm_broker",   "dispatch", "Send load acceptance confirmation to broker", requires_steps=[37]),
    Step(42, "nova.dispatch_email",       "dispatch", "Email dispatch sheet to driver and broker", requires_steps=[37]),
    Step(43, "signal.dispatch_sms",       "dispatch", "SMS load details to driver", requires_steps=[37]),
    Step(44, "orbit.start_tracking",      "dispatch", "Begin GPS tracking session for this load", requires_steps=[37]),
    Step(45, "audit.fuel_advance",        "dispatch", "Evaluate and approve/deny fuel advance request", requires_steps=[37]),
    Step(46, "dispatch.log_event",        "dispatch", "Write dispatch event to atomic ledger", requires_steps=[40]),
    Step(47, "sonny.post_loadboard",      "dispatch", "Post to DAT/Truckstop if spot load", requires_steps=[31]),
    Step(48, "dispatch.eta_calculate",    "dispatch", "Calculate ETA based on origin, destination, HOS", requires_steps=[34]),
    Step(49, "penny.margin_preview",      "dispatch", "Pre-dispatch margin preview (rate - fuel - driver %)", requires_steps=[33, 48]),
    Step(50, "dispatch.assign_load_id",   "dispatch", "Assign internal load ID and write to DB", requires_steps=[37]),
    Step(51, "dispatch.notify_shipper",   "dispatch", "Notify shipper of driver name, truck#, ETA", requires_steps=[37, 48]),
    Step(52, "dispatch.schedule_checkcall_1", "dispatch", "Schedule first check call (pickup +2hr)", requires_steps=[37]),
    Step(53, "dispatch.schedule_checkcall_2", "dispatch", "Schedule mid-transit check call", requires_steps=[37]),
    Step(54, "dispatch.schedule_checkcall_3", "dispatch", "Schedule pre-delivery check call", requires_steps=[37]),
    Step(55, "fleet.status_intransit",    "dispatch", "Update truck status to in_transit", requires_steps=[37]),
    Step(56, "document_vault.expect_bol", "dispatch", "Set expectation: BOL required within 2hr of pickup", requires_steps=[37]),
    Step(57, "dispatch.rate_lock",        "dispatch", "Lock rate — prevent re-negotiation post-dispatch", requires_steps=[41]),
    Step(58, "dispatch.insurance_check",  "dispatch", "Verify truck insurance current before dispatch", requires_steps=[6]),
    Step(59, "shield.pre_dispatch_safety","dispatch", "Pre-dispatch safety check (CSA, violations)", requires_steps=[37]),
    Step(60, "dispatch.complete",         "dispatch", "Mark dispatch complete — write atomic ledger event", requires_steps=[46, 55]),
)

# ── DOMAIN 3: IN-TRANSIT OPERATIONS (61–90) ──────────────────────────────────
_reg(
    Step(61, "transit.pickup_confirmed",  "transit", "Confirm pickup via GPS geofence or driver PWA tap"),
    Step(62, "document_vault.upload_bol", "transit", "Driver uploads BOL via PWA after pickup", requires_steps=[61]),
    Step(63, "scout.extract_bol",         "transit", "Scout extracts BOL data with Claude scanner", requires_steps=[62]),
    Step(64, "clm.link_bol_to_contract",  "transit", "Link BOL data to contract record", requires_steps=[63]),
    Step(65, "orbit.gps_ping_loop",       "transit", "Continuous GPS ping every 5 min from ELD", requires_steps=[61]),
    Step(66, "pulse.hos_monitor",         "transit", "Monitor driver HOS — alert at 2hr remaining", requires_steps=[65]),
    Step(67, "signal.hos_warning",        "transit", "SMS driver and Commander if HOS < 2hr", requires_steps=[66]),
    Step(68, "atlas.checkcall_1",         "transit", "Execute first automated check call via Bland AI", requires_steps=[52]),
    Step(69, "atlas.checkcall_2",         "transit", "Execute mid-transit check call via Bland AI", requires_steps=[53]),
    Step(70, "signal.delay_alert",        "transit", "Alert broker/shipper if ETA slips > 2hr", requires_steps=[65, 48]),
    Step(71, "orbit.geofence_delivery",   "transit", "Watch for truck entry into delivery geofence", requires_steps=[65]),
    Step(72, "atlas.checkcall_3",         "transit", "Execute pre-delivery check call", requires_steps=[54]),
    Step(73, "transit.weather_check",     "transit", "Check weather along route for delay risk", requires_steps=[65]),
    Step(74, "transit.traffic_check",     "transit", "Check traffic — update ETA if needed", requires_steps=[65]),
    Step(75, "signal.breakdown_detect",   "transit", "Detect breakdown: truck stopped >30min off-route", requires_steps=[65]),
    Step(76, "signal.emergency_escalate", "transit", "Escalate emergency via SMS to Commander", requires_steps=[75]),
    Step(77, "transit.detention_clock",   "transit", "Start detention timer if waiting >2hr at shipper", requires_steps=[61]),
    Step(78, "transit.detention_notify",  "transit", "Notify broker of detention accrual", requires_steps=[77]),
    Step(79, "transit.lumper_approve",    "transit", "Approve lumper receipt for reimbursement", requires_steps=[61]),
    Step(80, "penny.fuel_cost_track",     "transit", "Track fuel purchases via fuel card for this load", requires_steps=[61]),
    Step(81, "transit.mid_route_safety",  "transit", "Mid-route safety check — CSA score still valid", requires_steps=[65]),
    Step(82, "transit.broker_visibility", "transit", "Push live truck location to broker portal", requires_steps=[65]),
    Step(83, "transit.eta_sms_update",    "transit", "Send automated ETA update SMS to consignee", requires_steps=[74]),
    Step(84, "transit.dock_schedule",     "transit", "Auto-schedule dock appointment at destination", requires_steps=[48]),
    Step(85, "transit.hos_remaining",     "transit", "Calculate HOS hours remaining at destination", requires_steps=[66]),
    Step(86, "transit.border_crossing",   "transit", "Handle CTPAT/CBP docs if crossing border", requires_steps=[32]),
    Step(87, "transit.hazmat_compliance", "transit", "Verify hazmat placard and manifest if applicable", requires_steps=[32]),
    Step(88, "transit.temp_monitoring",   "transit", "Monitor reefer temperature for temp-sensitive loads", requires_steps=[65]),
    Step(89, "transit.cargo_claim_detect","transit", "Detect cargo claim risk from damage report", requires_steps=[61]),
    Step(90, "transit.complete",          "transit", "Mark transit complete on delivery geofence entry", requires_steps=[71]),
)

# ── DOMAIN 4: DELIVERY & SETTLEMENT (91–120) ─────────────────────────────────
_reg(
    Step(91,  "delivery.confirmed",          "settlement", "Confirm delivery via GPS geofence or driver PWA"),
    Step(92,  "document_vault.upload_pod",   "settlement", "Driver uploads POD via PWA", requires_steps=[91]),
    Step(93,  "scout.extract_pod",           "settlement", "Scout extracts POD data with Claude scanner", requires_steps=[92]),
    Step(94,  "clm.link_pod_to_contract",    "settlement", "Link POD to contract, set milestone to 100%", requires_steps=[93]),
    Step(95,  "clm.trigger_invoice",         "settlement", "Trigger invoice generation from contract", requires_steps=[94]),
    Step(96,  "echo.missing_doc_check",      "settlement", "If delivered but no POD in 4hr → SMS nudge", requires_steps=[91]),
    Step(97,  "settler.calc_driver_pay",     "settlement", "Calculate driver gross pay (rate% minus deductions)", requires_steps=[95]),
    Step(98,  "settler.fuel_deduction",      "settlement", "Apply fuel card deductions to settlement", requires_steps=[80, 97]),
    Step(99,  "settler.escrow_check",        "settlement", "Check escrow balance and apply if applicable", requires_steps=[97]),
    Step(100, "settler.lumper_reimbursement","settlement", "Add lumper reimbursement to settlement", requires_steps=[79, 97]),
    Step(101, "settler.detention_add",       "settlement", "Add approved detention pay to settlement", requires_steps=[78, 97]),
    Step(102, "settler.advance_deduct",      "settlement", "Deduct fuel/cash advances from settlement", requires_steps=[45, 97]),
    Step(103, "settler.net_pay_calc",        "settlement", "Calculate final net driver pay", requires_steps=[97, 98, 99, 100, 101, 102]),
    Step(104, "penny.load_margin",           "settlement", "Calculate final load margin (gross minus all costs)", requires_steps=[103]),
    Step(105, "settler.ach_initiate",        "settlement", "Initiate ACH payment to driver bank account", requires_steps=[103, 11]),
    Step(106, "nova.settlement_email",       "settlement", "Email settlement statement to driver", requires_steps=[103]),
    Step(107, "factoring.submit_invoice",    "settlement", "Submit invoice to factoring company", requires_steps=[95]),
    Step(108, "factoring.track_payment",     "settlement", "Track factoring payment status", requires_steps=[107]),
    Step(109, "clm.mark_gl_posted",          "settlement", "Mark contract as GL posted in accounting", requires_steps=[95]),
    Step(110, "penny.update_mtd_kpis",       "settlement", "Update MTD KPIs: gross, margin, RPM", requires_steps=[104]),
    Step(111, "fleet.status_available",      "settlement", "Set truck status back to available", requires_steps=[91]),
    Step(112, "dispatch.next_load_offer",    "settlement", "Proactively offer next load within 50mi", requires_steps=[111]),
    Step(113, "audit.settlement_audit",      "settlement", "Audit settlement for SOD compliance", requires_steps=[105]),
    Step(114, "beacon.update_load_history",  "settlement", "Update load history in EAGLE EYE", requires_steps=[110]),
    Step(115, "atomic_ledger.settlement",    "settlement", "Write complete settlement event to atomic ledger", requires_steps=[109, 110]),
    Step(116, "driver.performance_score",    "settlement", "Update driver performance score after delivery", requires_steps=[91, 93]),
    Step(117, "carrier.revenue_update",      "settlement", "Update carrier MTD revenue record", requires_steps=[110]),
    Step(118, "nova.broker_invoice_email",   "settlement", "Email invoice/POD package to broker", requires_steps=[93, 95]),
    Step(119, "dispute.check_variance",      "settlement", "Check if paid amount matches rate confirmation", requires_steps=[108, 95]),
    Step(120, "settlement.complete",         "settlement", "Mark settlement complete, archive to vault", requires_steps=[115]),
)

# ── DOMAIN 5: CONTRACT LIFECYCLE MANAGEMENT (121–150) ────────────────────────
_reg(
    Step(121, "clm.email_inbound_parse",   "clm", "Parse SendGrid inbound email for contract attachments"),
    Step(122, "clm.doc_classify",          "clm", "Classify document type: rate_conf/bol/pod/agreement", requires_steps=[121]),
    Step(123, "clm.extract_variables",     "clm", "Run Claude scanner to extract 100+ contract variables", requires_steps=[122]),
    Step(124, "clm.digital_twin_create",   "clm", "Create contract digital twin in Supabase", requires_steps=[123]),
    Step(125, "clm.revenue_leakage_check", "clm", "Compare actual billing vs. contract terms", requires_steps=[124]),
    Step(126, "clm.counterparty_lookup",   "clm", "Lookup broker/shipper in carrier records DB", requires_steps=[124]),
    Step(127, "clm.duplicate_detect",      "clm", "Detect duplicate rate confirmations (same load#)", requires_steps=[124]),
    Step(128, "clm.expiry_schedule",       "clm", "Schedule alerts for contract/agreement expiry", requires_steps=[124]),
    Step(129, "clm.broker_blacklist_check","clm", "Check broker against known bad-pay list", requires_steps=[126]),
    Step(130, "clm.rate_benchmark",        "clm", "Compare rate against DAT/Truckstop spot market", requires_steps=[123]),
    Step(131, "clm.auto_approve",          "clm", "Auto-approve contract if confidence >90% and no warnings", requires_steps=[125, 129, 130]),
    Step(132, "clm.flag_for_review",       "clm", "Flag contract for Commander review if warnings exist", requires_steps=[123]),
    Step(133, "clm.milestone_10pct",       "clm", "Set milestone 10% on load assignment", requires_steps=[124]),
    Step(134, "clm.milestone_50pct",       "clm", "Set milestone 50% on pickup confirmed", requires_steps=[133]),
    Step(135, "clm.milestone_90pct",       "clm", "Set milestone 90% on POD uploaded", requires_steps=[134]),
    Step(136, "clm.milestone_100pct",      "clm", "Set milestone 100% on invoice paid", requires_steps=[135]),
    Step(137, "clm.gl_trigger",            "clm", "Trigger GL/accounting entry at 100% milestone", requires_steps=[136]),
    Step(138, "clm.factoring_eligibility", "clm", "Check contract eligibility for factoring", requires_steps=[124]),
    Step(139, "clm.broker_agreement_link", "clm", "Link rate confirmation to master broker agreement", requires_steps=[124]),
    Step(140, "clm.payment_terms_enforce", "clm", "Enforce payment terms — flag if overdue", requires_steps=[124]),
    Step(141, "clm.dispute_open",          "clm", "Open dispute record if payment variance detected", requires_steps=[119]),
    Step(142, "clm.dispute_escalate",      "clm", "Escalate dispute to Commander after 5 business days", requires_steps=[141]),
    Step(143, "clm.archive_executed",      "clm", "Archive fully executed contract with all documents", requires_steps=[136]),
    Step(144, "clm.analytics_update",      "clm", "Update CLM analytics: avg rate/mi, payment cycle time", requires_steps=[136]),
    Step(145, "clm.broker_scorecard",      "clm", "Update broker reliability scorecard", requires_steps=[136]),
    Step(146, "clm.volume_discount_check", "clm", "Check if broker qualifies for volume discount tier", requires_steps=[145]),
    Step(147, "clm.auto_renew_agreement",  "clm", "Auto-renew expired broker agreement if in good standing", requires_steps=[128]),
    Step(148, "clm.contract_export",       "clm", "Export contract package (PDF+JSON) for enterprise clients", requires_steps=[143]),
    Step(149, "clm.compliance_audit",      "clm", "Run compliance audit on contract (SOD, GAAP mapping)", requires_steps=[143]),
    Step(150, "clm.complete",              "clm", "Mark CLM workflow complete — write atomic ledger event", requires_steps=[143, 144]),
)

# ── DOMAIN 6: COMPLIANCE & SAFETY (151–180) ──────────────────────────────────
_reg(
    Step(151, "shield.daily_sweep",        "compliance", "Daily sweep of all 1000 trucks for safety status"),
    Step(152, "shield.csa_refresh",        "compliance", "Refresh CSA BASIC scores weekly from FMCSA", requires_steps=[151]),
    Step(153, "shield.insurance_30d",      "compliance", "Alert 30 days before insurance expiry", requires_steps=[151]),
    Step(154, "shield.insurance_7d",       "compliance", "Urgent alert 7 days before insurance expiry", requires_steps=[153]),
    Step(155, "shield.insurance_expired",  "compliance", "Auto-suspend carrier if insurance expired", requires_steps=[154]),
    Step(156, "shield.mc_authority_check", "compliance", "Verify MC authority still active in FMCSA SAFER", requires_steps=[151]),
    Step(157, "shield.cdl_expiry_check",   "compliance", "Check CDL expiry for all active drivers", requires_steps=[151]),
    Step(158, "shield.cdl_expiry_30d",     "compliance", "Alert driver and carrier 30 days before CDL expiry", requires_steps=[157]),
    Step(159, "shield.cdl_expiry_7d",      "compliance", "Urgent alert 7 days before CDL expiry — suspend if expired", requires_steps=[158]),
    Step(160, "shield.drug_test_schedule", "compliance", "Schedule random drug testing per DOT requirements", requires_steps=[151]),
    Step(161, "shield.accident_flag",      "compliance", "Flag carrier with DOT accident report in last 12mo", requires_steps=[152]),
    Step(162, "shield.oos_rate_check",     "compliance", "Flag if Out-of-Service rate exceeds 20% threshold", requires_steps=[152]),
    Step(163, "shield.safety_light_update","compliance", "Update safety light color based on all compliance factors", requires_steps=[152, 156, 157]),
    Step(164, "shield.red_light_suspend",  "compliance", "Block load offers to red-light carriers", requires_steps=[163]),
    Step(165, "nova.compliance_email",     "compliance", "Email compliance status report to carrier", requires_steps=[163]),
    Step(166, "signal.compliance_sms",     "compliance", "SMS carrier if safety light turns yellow or red", requires_steps=[163]),
    Step(167, "shield.hazmat_cert_check",  "compliance", "Verify hazmat endorsement for hazmat trucks", requires_steps=[151]),
    Step(168, "shield.oversize_permit",    "compliance", "Verify oversize/overweight permits are current", requires_steps=[151]),
    Step(169, "shield.ifta_compliance",    "compliance", "Check IFTA quarterly filing status", requires_steps=[151]),
    Step(170, "shield.ucr_registration",   "compliance", "Verify UCR registration is current", requires_steps=[151]),
    Step(171, "shield.annual_inspection",  "compliance", "Track annual vehicle inspection compliance", requires_steps=[151]),
    Step(172, "shield.dot_audit_prep",     "compliance", "Generate DOT audit readiness report", requires_steps=[152, 163]),
    Step(173, "shield.eld_mandate_check",  "compliance", "Verify ELD mandate compliance for all trucks", requires_steps=[151]),
    Step(174, "shield.cargo_insurance",    "compliance", "Verify per-load cargo insurance meets broker minimum", requires_steps=[32]),
    Step(175, "shield.new_entrant_monitor","compliance", "Monitor new authority carriers (<12 months) for violations", requires_steps=[3]),
    Step(176, "shield.driver_mvr_check",   "compliance", "Annual MVR check for all drivers", requires_steps=[151]),
    Step(177, "shield.lease_agreement",    "compliance", "Verify owner-operator lease agreements are current", requires_steps=[151]),
    Step(178, "shield.escrow_audit",       "compliance", "Audit escrow accounts for regulatory compliance", requires_steps=[99]),
    Step(179, "shield.compliance_score",   "compliance", "Calculate composite compliance score (0–100) per carrier", requires_steps=[163, 169, 170, 171]),
    Step(180, "compliance.complete",       "compliance", "Write compliance cycle results to atomic ledger", requires_steps=[179]),
)

# ── DOMAIN 7: ANALYTICS & INTELLIGENCE (181–200) ─────────────────────────────
_reg(
    Step(181, "analytics.daily_kpi",        "analytics", "Refresh all KPIs: gross, margin, RPM, utilization"),
    Step(182, "analytics.fleet_utilization","analytics", "Calculate fleet utilization rate (active/total)", requires_steps=[181]),
    Step(183, "analytics.lane_profitability","analytics", "Analyze profitability by lane (origin-dest pair)", requires_steps=[181]),
    Step(184, "analytics.broker_performance","analytics", "Rank brokers by pay speed, rate quality, dispute rate", requires_steps=[144, 145]),
    Step(185, "analytics.driver_ranking",   "analytics", "Update driver performance ranking", requires_steps=[116]),
    Step(186, "analytics.revenue_forecast", "analytics", "30/60/90-day revenue forecast from load history", requires_steps=[183]),
    Step(187, "analytics.fuel_analysis",    "analytics", "Analyze fuel cost trends and efficiency by truck", requires_steps=[80]),
    Step(188, "analytics.dead_head_report", "analytics", "Report dead-head miles per truck", requires_steps=[182]),
    Step(189, "analytics.detention_report", "analytics", "Summarize detention events by broker/shipper", requires_steps=[78]),
    Step(190, "analytics.spot_vs_contract", "analytics", "Compare spot vs. contract rate performance", requires_steps=[130]),
    Step(191, "analytics.cash_flow",        "analytics", "Project cash flow based on factoring and settlement cycles", requires_steps=[186]),
    Step(192, "analytics.carrier_ltv",      "analytics", "Calculate carrier lifetime value (subscription + load revenue)", requires_steps=[117]),
    Step(193, "analytics.csa_trend",        "analytics", "Track CSA score trends — predict carrier risk trajectory", requires_steps=[152]),
    Step(194, "analytics.rate_index",       "analytics", "Build internal rate index from all executed rate confs", requires_steps=[150]),
    Step(195, "analytics.equipment_demand", "analytics", "Forecast equipment demand by type", requires_steps=[183]),
    Step(196, "analytics.compliance_risk",  "analytics", "Score fleet compliance risk for insurance renewal", requires_steps=[179]),
    Step(197, "analytics.weekly_report",    "analytics", "Generate weekly executive report for Commander", requires_steps=[181, 182, 183]),
    Step(198, "analytics.airtable_sync",    "analytics", "Sync analytics summary to Airtable", requires_steps=[197]),
    Step(199, "analytics.sentry_health",    "analytics", "Check Sentry error rates and alert if elevated"),
    Step(200, "analytics.complete",         "analytics", "Mark analytics cycle complete — write atomic ledger event", requires_steps=[197]),
)

# ── DOMAIN 8: LIGHT FLEET ONBOARDING (201–220) ───────────────────────────────
_reg(
    Step(201, "lf.intake.receive",              "lf_onboarding", "Receive light fleet driver application"),
    Step(202, "lf.intake.validate_license",     "lf_onboarding", "Validate driver license number, state, expiry", requires_steps=[201]),
    Step(203, "lf.intake.run_mvr",              "lf_onboarding", "Run Motor Vehicle Record (MVR) check", requires_steps=[202]),
    Step(204, "lf.intake.run_background",       "lf_onboarding", "Run background screening check", requires_steps=[203]),
    Step(205, "lf.intake.verify_insurance",     "lf_onboarding", "Verify vehicle insurance not expired", requires_steps=[201]),
    Step(206, "lf.intake.classify_vehicle",     "lf_onboarding", "Classify vehicle type: SUV / sedan / cargo_van / luxury", requires_steps=[201]),
    Step(207, "lf.intake.assign_services",      "lf_onboarding", "Assign approved service types (NEMT/executive/courier/gig)", requires_steps=[203, 204, 205]),
    Step(208, "lf.intake.create_profile",       "lf_onboarding", "Activate driver profile in light_vehicle_drivers table", requires_steps=[207]),
    Step(209, "lf.intake.send_welcome_sms",     "lf_onboarding", "Send welcome SMS to new driver", requires_steps=[208]),
    Step(210, "lf.intake.activate_app",         "lf_onboarding", "Activate driver PWA app access", requires_steps=[208]),
    Step(211, "lf.nemt.verify_eligibility",     "lf_onboarding", "Verify NEMT Medicaid/Medicare eligibility if applicable", requires_steps=[207]),
    Step(212, "lf.nemt.create_client",          "lf_onboarding", "Create NEMT client profile if patient data provided", requires_steps=[211]),
    Step(213, "lf.exec.create_account",         "lf_onboarding", "Create executive corporate account if applicable", requires_steps=[207]),
    Step(214, "lf.exec.set_rates",              "lf_onboarding", "Set corporate rate agreements", requires_steps=[213]),
    Step(215, "lf.intake.add_to_pool",          "lf_onboarding", "Add driver to active dispatch pool", requires_steps=[208]),
    Step(216, "lf.intake.notify_eagle_eye",     "lf_onboarding", "Push new driver notification to Eagle Eye dashboard", requires_steps=[215]),
    Step(217, "lf.intake.ledger_write",         "lf_onboarding", "Write driver onboarding event to atomic ledger", requires_steps=[208]),
    Step(218, "lf.intake.compliance_baseline",  "lf_onboarding", "Establish initial compliance score for driver", requires_steps=[203, 204, 205]),
    Step(219, "lf.intake.vault_setup",          "lf_onboarding", "Create document vault folder for driver", requires_steps=[208]),
    Step(220, "lf.intake.onboarding_complete",  "lf_onboarding", "Mark driver onboarding workflow complete", requires_steps=[215, 216, 217, 218, 219]),
)

# ── DOMAIN 9: LIGHT FLEET TRIP DISPATCH (221–240) ────────────────────────────
_reg(
    Step(221, "lf.trip.receive",                "lf_dispatch", "Receive new light fleet trip request"),
    Step(222, "lf.trip.validate_addresses",     "lf_dispatch", "Validate pickup and dropoff addresses", requires_steps=[221]),
    Step(223, "lf.trip.classify_type",          "lf_dispatch", "Confirm trip type: NEMT / executive / courier / gig", requires_steps=[221]),
    Step(224, "lf.trip.estimate_distance",      "lf_dispatch", "Estimate trip distance in miles and ETA", requires_steps=[222]),
    Step(225, "lf.trip.calculate_rate",         "lf_dispatch", "Calculate trip rate if not manually set", requires_steps=[224]),
    Step(226, "lf.trip.check_nemt_auth",        "lf_dispatch", "Verify NEMT insurance pre-authorization exists", requires_steps=[223]),
    Step(227, "lf.trip.match_driver",           "lf_dispatch", "Match nearest approved available driver", requires_steps=[223, 225]),
    Step(228, "lf.trip.offer_driver",           "lf_dispatch", "Send trip offer to matched driver via app", requires_steps=[227]),
    Step(229, "lf.trip.confirm_acceptance",     "lf_dispatch", "Confirm driver acceptance and lock assignment", requires_steps=[228]),
    Step(230, "lf.trip.lock_assignment",        "lf_dispatch", "Lock driver_id and set status=assigned", requires_steps=[229]),
    Step(231, "lf.trip.notify_passenger",       "lf_dispatch", "Send SMS/email confirmation to passenger or client", requires_steps=[230]),
    Step(232, "lf.trip.start_gps",             "lf_dispatch", "Start GPS tracking session for trip", requires_steps=[230]),
    Step(233, "lf.trip.doc_expectation",        "lf_dispatch", "Create POD document expectation for trip", requires_steps=[230]),
    Step(234, "lf.trip.notify_corporate",       "lf_dispatch", "Notify corporate account of executive booking", requires_steps=[230]),
    Step(235, "lf.trip.log_auth_code",          "lf_dispatch", "Log NEMT insurance auth code to trip record", requires_steps=[226]),
    Step(236, "lf.trip.dispatch_email",         "lf_dispatch", "Send internal dispatch confirmation email", requires_steps=[230]),
    Step(237, "lf.trip.ledger_preview",         "lf_dispatch", "Write projected revenue to atomic ledger", requires_steps=[225]),
    Step(238, "lf.trip.eta_broadcast",          "lf_dispatch", "Broadcast ETA to driver and passenger", requires_steps=[224, 231]),
    Step(239, "lf.trip.dispatch_complete",      "lf_dispatch", "Mark trip dispatch workflow complete", requires_steps=[231, 232, 236, 237]),
    Step(240, "lf.trip.eagle_eye_update",       "lf_dispatch", "Refresh Eagle Eye light fleet board", requires_steps=[239]),
)

# ── DOMAIN 10: LIGHT FLEET TRIP TRANSIT (241–255) ────────────────────────────
_reg(
    Step(241, "lf.transit.en_route",            "lf_transit", "Driver starts trip — GPS active"),
    Step(242, "lf.transit.pickup_confirmed",    "lf_transit", "Driver arrives at pickup location", requires_steps=[241]),
    Step(243, "lf.transit.passenger_aboard",    "lf_transit", "Passenger aboard — status → in_progress", requires_steps=[242]),
    Step(244, "lf.transit.gps_ping",           "lf_transit", "Continuous GPS ping loop — 30s interval", requires_steps=[241]),
    Step(245, "lf.transit.eta_recalculate",     "lf_transit", "Recalculate live ETA every 5 minutes", requires_steps=[244]),
    Step(246, "lf.transit.delay_detection",     "lf_transit", "Flag if ETA drifts more than 15 minutes", requires_steps=[245]),
    Step(247, "lf.transit.mobility_assist",     "lf_transit", "Log wheelchair/stretcher assist for NEMT trips", requires_steps=[243]),
    Step(248, "lf.transit.flight_monitor",      "lf_transit", "Monitor flight status for executive airport trips", requires_steps=[241]),
    Step(249, "lf.transit.detention_check",     "lf_transit", "Flag driver waiting beyond threshold", requires_steps=[242]),
    Step(250, "lf.transit.mid_trip_sms",        "lf_transit", "Send mid-trip status SMS to passenger", requires_steps=[244]),
    Step(251, "lf.transit.geofence_arrival",    "lf_transit", "Detect driver approaching dropoff location", requires_steps=[244]),
    Step(252, "lf.transit.dropoff_confirmed",   "lf_transit", "Driver confirms arrival at dropoff", requires_steps=[251]),
    Step(253, "lf.transit.pod_capture",         "lf_transit", "Driver uploads proof of delivery / completion photo", requires_steps=[252]),
    Step(254, "lf.transit.trip_complete",       "lf_transit", "Mark trip completed — write completed_at timestamp", requires_steps=[253]),
    Step(255, "lf.transit.transit_complete",    "lf_transit", "Transit domain workflow complete", requires_steps=[254]),
)

# ── DOMAIN 11: LIGHT FLEET TRIP SETTLEMENT (256–270) ─────────────────────────
_reg(
    Step(256, "lf.settle.confirm_completion",   "lf_settlement", "Verify trip completed and POD captured"),
    Step(257, "lf.settle.apply_rate",           "lf_settlement", "Calculate and confirm final trip rate", requires_steps=[256]),
    Step(258, "lf.settle.platform_fee",         "lf_settlement", "Deduct platform fee (8% Starter / 3% Pro)", requires_steps=[257]),
    Step(259, "lf.settle.driver_net",           "lf_settlement", "Calculate driver net earnings after fee", requires_steps=[258]),
    Step(260, "lf.settle.nemt_billing",         "lf_settlement", "Queue NEMT trip for Medicaid/Medicare billing", requires_steps=[257]),
    Step(261, "lf.settle.corporate_invoice",    "lf_settlement", "Generate invoice for corporate executive account", requires_steps=[257]),
    Step(262, "lf.settle.ach_initiation",       "lf_settlement", "Initiate ACH driver payout via Stripe", requires_steps=[259]),
    Step(263, "lf.settle.ledger_write",         "lf_settlement", "Write settlement event to atomic ledger", requires_steps=[259]),
    Step(264, "lf.settle.driver_performance",   "lf_settlement", "Update driver rating and total_trips counter", requires_steps=[256]),
    Step(265, "lf.settle.client_receipt",       "lf_settlement", "Send receipt SMS/email to passenger or client", requires_steps=[257]),
    Step(266, "lf.settle.kpi_update",           "lf_settlement", "Increment light fleet MTD KPI counters", requires_steps=[263]),
    Step(267, "lf.settle.nemt_audit_log",       "lf_settlement", "Write Medicaid-compliant audit log for NEMT trip", requires_steps=[260]),
    Step(268, "lf.settle.dispute_check",        "lf_settlement", "Flag disputes or rate mismatches", requires_steps=[257]),
    Step(269, "lf.settle.invoice_record",       "lf_settlement", "Write invoice record to invoices table", requires_steps=[261]),
    Step(270, "lf.settle.settlement_complete",  "lf_settlement", "Settlement domain workflow complete", requires_steps=[262, 263, 265, 266, 267]),
)

# ── DOMAIN 12: LIGHT FLEET LOAD HUNT (271–290) ───────────────────────────────
_reg(
    Step(271, "lf.hunt.read_agent_card",        "lf_load_hunt", "Read driver agent card: vehicle type, rates, service areas, availability"),
    Step(272, "lf.hunt.build_search_params",    "lf_load_hunt", "Map agent card to loadboard search parameters", requires_steps=[271]),
    Step(273, "lf.hunt.scan_123loadboard",      "lf_load_hunt", "Scan 123Loadboard for matching loads", requires_steps=[272]),
    Step(274, "lf.hunt.scan_dat",               "lf_load_hunt", "Scan DAT One for matching loads", requires_steps=[272]),
    Step(275, "lf.hunt.scan_truckstop",         "lf_load_hunt", "Scan Truckstop.com for matching loads", requires_steps=[272]),
    Step(276, "lf.hunt.scan_truckerpath",       "lf_load_hunt", "Scan TruckerPath for matching loads", requires_steps=[272]),
    Step(277, "lf.hunt.scan_chrobinson",        "lf_load_hunt", "Scan C.H. Robinson Navisphere for matching loads", requires_steps=[272]),
    Step(278, "lf.hunt.deduplicate",            "lf_load_hunt", "Deduplicate results across boards by load_id", requires_steps=[273, 274, 275, 276, 277]),
    Step(279, "lf.hunt.score_loads",            "lf_load_hunt", "Score each load: RPM, deadhead, pickup date, broker rating", requires_steps=[278]),
    Step(280, "lf.hunt.filter_hot",             "lf_load_hunt", "Flag HOT loads above driver auto-accept threshold", requires_steps=[279]),
    Step(281, "lf.hunt.persist_results",        "lf_load_hunt", "Upsert matched loads to load_hunter_results with driver_id", requires_steps=[280]),
    Step(282, "lf.hunt.auto_accept",            "lf_load_hunt", "Auto-accept HOT loads if driver auto-accept is enabled", requires_steps=[281]),
    Step(283, "lf.hunt.notify_driver",          "lf_load_hunt", "SMS driver with top 3 matched loads", requires_steps=[281]),
    Step(284, "lf.hunt.notify_eagle_eye",       "lf_load_hunt", "Push matched load count to Eagle Eye dashboard", requires_steps=[281]),
    Step(285, "lf.hunt.update_driver_stats",    "lf_load_hunt", "Update driver last_hunted_at and matched_loads_count", requires_steps=[281]),
    Step(286, "lf.hunt.schedule_next",          "lf_load_hunt", "Schedule next hunt cycle (default: 15 min)", requires_steps=[285]),
    Step(287, "lf.hunt.rate_index_update",      "lf_load_hunt", "Feed accepted rates into internal rate index", requires_steps=[282]),
    Step(288, "lf.hunt.broker_blacklist_check", "lf_load_hunt", "Skip loads from blacklisted brokers", requires_steps=[278]),
    Step(289, "lf.hunt.ledger_write",           "lf_load_hunt", "Write hunt event to atomic ledger", requires_steps=[285]),
    Step(290, "lf.hunt.hunt_complete",          "lf_load_hunt", "Mark load hunt cycle complete", requires_steps=[283, 284, 285, 286, 289]),
)
